### ISSUE TITLE
Get a corrupted Gif when using Mono 4.6 on MacOS 

### ISSUE THREAD

**Issue by emmekappa** [DataDink/Bumpkit#10]
seems that on line 157 of `GifEncoder.cs`:
`var dataLength = sourceGif.ReadByte();`

`dataLength` is zero and the loop to write the frame never starts.

The same code works well on Windows.

**Comment by DataDink** [comment]
Bumpkit is a wrapper around gdi/+ which I don't believe is available on MacOS
